"""creacion is active1

Revision ID: 479a1fce1467
Revises: b89dcb22fd6e
Create Date: 2023-10-27 17:22:56.625722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '479a1fce1467'
down_revision: Union[str, None] = 'b89dcb22fd6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movements_movement_id', table_name='movements')
    op.drop_index('ix_movements_name', table_name='movements')
    op.drop_table('movements')
    op.drop_index('ix_blog_description', table_name='blog')
    op.drop_index('ix_blog_publication_id', table_name='blog')
    op.drop_table('blog')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.create_table('blog',
    sa.Column('publication_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_blog', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('url_video', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('url_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_publication', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('publication_id', name='blog_pkey')
    )
    op.create_index('ix_blog_publication_id', 'blog', ['publication_id'], unique=False)
    op.create_index('ix_blog_description', 'blog', ['description'], unique=False)
    op.create_table('movements',
    sa.Column('movement_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coins', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='movements_user_id_fkey'),
    sa.PrimaryKeyConstraint('movement_id', name='movements_pkey')
    )
    op.create_index('ix_movements_name', 'movements', ['name'], unique=False)
    op.create_index('ix_movements_movement_id', 'movements', ['movement_id'], unique=False)
    # ### end Alembic commands ###
