"""borrar  no hago pull

Revision ID: 4c1ee96ee7ee
Revises: 85eac4e1cc25
Create Date: 2023-10-27 18:12:48.341662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c1ee96ee7ee'
down_revision: Union[str, None] = '85eac4e1cc25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movements_movement_id', table_name='movements')
    op.drop_index('ix_movements_name', table_name='movements')
    op.drop_table('movements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movements',
    sa.Column('movement_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coins', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('no_hago_pull', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='movements_user_id_fkey'),
    sa.PrimaryKeyConstraint('movement_id', name='movements_pkey')
    )
    op.create_index('ix_movements_name', 'movements', ['name'], unique=False)
    op.create_index('ix_movements_movement_id', 'movements', ['movement_id'], unique=False)
    # ### end Alembic commands ###
