"""borrar recocha

Revision ID: 6d35b8662ce1
Revises: 1770c9602421
Create Date: 2023-10-27 18:06:04.941358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d35b8662ce1'
down_revision: Union[str, None] = '1770c9602421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movements_movement_id', table_name='movements')
    op.drop_index('ix_movements_name', table_name='movements')
    op.drop_table('movements')
    op.drop_column('blog', 'recocha')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('recocha', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('movements',
    sa.Column('movement_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coins', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='movements_user_id_fkey'),
    sa.PrimaryKeyConstraint('movement_id', name='movements_pkey')
    )
    op.create_index('ix_movements_name', 'movements', ['name'], unique=False)
    op.create_index('ix_movements_movement_id', 'movements', ['movement_id'], unique=False)
    # ### end Alembic commands ###
