"""Aguacates

Revision ID: 6f254ff1dd52
Revises: 4c1ee96ee7ee
Create Date: 2023-10-27 18:18:17.193154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f254ff1dd52'
down_revision: Union[str, None] = '4c1ee96ee7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('aguacate', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movements', 'aguacate')
    # ### end Alembic commands ###
