"""Aguacates fuera

Revision ID: a5b4d1c1bddf
Revises: 6f254ff1dd52
Create Date: 2023-10-27 18:20:30.534136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b4d1c1bddf'
down_revision: Union[str, None] = '6f254ff1dd52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movements', 'aguacate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('aguacate', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
