"""agregando recocha2_0

Revision ID: 6d72b7b5a6ba
Revises: 
Create Date: 2023-10-28 00:56:37.881715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d72b7b5a6ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prize', sa.Column('recocha2_0', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prize', 'recocha2_0')
    # ### end Alembic commands ###
