"""pull prueba

Revision ID: 816624e7f6a7
Revises: 
Create Date: 2023-10-27 18:57:06.492939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816624e7f6a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('type_blog', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('url_video', sa.String(length=255), nullable=True),
    sa.Column('url_image', sa.String(length=255), nullable=True),
    sa.Column('date_publication', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('publication_id')
    )
    op.create_index(op.f('ix_blog_description'), 'blog', ['description'], unique=False)
    op.create_index(op.f('ix_blog_publication_id'), 'blog', ['publication_id'], unique=False)
    op.create_table('prize',
    sa.Column('prize_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.Column('url_image', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('prize_id')
    )
    op.create_index(op.f('ix_prize_name'), 'prize', ['name'], unique=False)
    op.create_index(op.f('ix_prize_prize_id'), 'prize', ['prize_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('movements',
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    op.create_index(op.f('ix_movements_movement_id'), 'movements', ['movement_id'], unique=False)
    op.create_index(op.f('ix_movements_name'), 'movements', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movements_name'), table_name='movements')
    op.drop_index(op.f('ix_movements_movement_id'), table_name='movements')
    op.drop_table('movements')
    op.drop_table('users')
    op.drop_index(op.f('ix_prize_prize_id'), table_name='prize')
    op.drop_index(op.f('ix_prize_name'), table_name='prize')
    op.drop_table('prize')
    op.drop_index(op.f('ix_blog_publication_id'), table_name='blog')
    op.drop_index(op.f('ix_blog_description'), table_name='blog')
    op.drop_table('blog')
    # ### end Alembic commands ###
