"""eliminando recocha2_0

Revision ID: e34d0a175689
Revises: 6d72b7b5a6ba
Create Date: 2023-10-28 00:57:58.507931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34d0a175689'
down_revision: Union[str, None] = '6d72b7b5a6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prize', 'recocha2_0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prize', sa.Column('recocha2_0', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
